# Generated by Django 4.0.5 on 2022-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_ticker_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='companyName',
            field=models.CharField(default='companyName', max_length=100),
        ),
    ]
